# Generated by Django 4.1.7 on 2026-05-15 08:12

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='activity',
                    name='id',
                    field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='leaderboard',
                    name='id',
                    field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='team',
                    name='id',
                    field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='id',
                    field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='workout',
                    name='id',
                    field=djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
